application:
  title: ${APPLICATION_TITLE:VectoPath Referential API}
  version: ${APPLICATION_VERSION:@project.version@}

spring:
  application:
    name: VectoPath Referential API

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8090/realms/master}


  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/vecto_path}
    username: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: ${DATABASE_DRIVER:org.postgresql.Driver}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:none}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:false}
    open-in-view: ${JPA_OPEN_IN_VIEW:false}

security:
  scopes:
    referential:
      read: ${SECURITY_SCOPE_THIRD_PARTY_REF_READ:referential.read}
      write: ${SECURITY_SCOPE_THIRD_PARTY_REF_WRITE:referential.write}
      delete: ${SECURITY_SCOPE_THIRD_PARTY_REF_DELETE:referential.delete}
      admin: ${SECURITY_SCOPE_THIRD_PARTY_REF_ADMIN:referential.admin}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost,http://localhost:3000,http://localhost:4200,http://localhost:8080,http://localhost:9000}
    allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,PATCH,DELETE,OPTIONS}
    allowed-headers: ${CORS_ALLOWED_HEADERS:Authorization,Content-Type,X-Requested-With,Accept,Origin,Access-Control-Request-Method,Access-Control-Request-Headers}
    exposed-headers: ${CORS_EXPOSED_HEADERS:Access-Control-Allow-Origin,Access-Control-Allow-Credentials}
    allow-credentials: ${CORS_ALLOW_CREDENTIALS:false}
    max-age: ${CORS_MAX_AGE:3600}


server:
  port: ${SERVER_PORT:8083}

spring.jackson:
  time-zone: ${JACKSON_TIME_ZONE:UTC}

logging:
  level:
    com.laulem.vectopath: ${LOGGING_LEVEL_VECTOPATH:INFO}
    org.springframework.ai: ${LOGGING_LEVEL_SPRING_AI:INFO}
  pattern:
    console: "${LOGGING_PATTERN_CONSOLE:%d{yyyy-MM-dd HH:mm:ss} - %msg%n}"

management:
  info:
    ssl:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  health:
    db:
      enabled: true
  otlp:
    metrics:
      export:
        enabled: false
