version: '3.8'

services:
  vecto-path-pgvector-db:
    build:
      context: .
      dockerfile: vecto-path-pgvector-db.dockerfile
    container_name: vecto-path-pgvector-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vecto_path
    ports:
      - "5432:5432"
    volumes:
      - ../database/pg-init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
